### ISSUE TITLE
The _transform function needs to be broken up a bit

### ISSUE THREAD

**Issue by wolfeidau** [deoxxa/dissolve#5]
https://github.com/deoxxa/dissolve/blob/master/index.js#L46-L218

As v8 only gives you pointers to which function is consuming all the time it is hard to nail down which part is performing poorly. Also I believe this function will never be fully optimised as it is way too long, this leads to a lot of unnecessary allocations.

**Comment by arthurschreiber** [comment]
I did some profiling, and V8 optimizes the `#_transform` method without any problems. I still found that breaking it up makes it easier to understand where time is spent when profiling, and I've not seen any negative performance impacts. See https://github.com/deoxxa/dissolve/pull/9.

**Comment by wolfeidau** [comment]
The performance issues you used to see with V8 around this sort of thing was more around constantly ballooning memory and leaks than actual throughput.

Older v8 versions capped the length of functions which would be optimised. To observe this you can enable tracing for v8 and see how that function is optimised/deomptimised while your running tests.

In our case we had quite large complex data structures which got handed around a bit before cleanup so that also seemed to trigger increased memory use.

Either way V8 loves short simple code and more readily optimises it.

Good luck with your profiling!

**Comment by arthurschreiber** [comment]
Closed by #9.
